// <auto-generated />
namespace Vintagerie.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Product_AND_Categories : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Product_AND_Categories));
        
        string IMigrationMetadata.Id
        {
            get { return "201611081850292_Product_AND_Categories"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
